[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_fall_transfer_hook = "3ryTbMdzMNquLBm9BdZYe93JnezkVkypGBqb1yp4n8FG"
token-mover = "J2q1RQvwr41WTPeVSn4DKxd2u4Fs7n8NMKp7fmbhmodp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
